# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
      # - image: circleci/node:7
      # - image: circleci/node:8
      # - image: circleci/node:9
      # - image: circleci/node:node-browsers
      # - image: circleci/node:latest-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - dep-cache-{{ checksum "package.json" }}
          - dep-cache-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dep-cache-{{ checksum "package.json" }}

      # - run: yarn lint
      - run: yarn test
